use_frameworks!

platform :ios, '9.0'

target 'HandTracker_Example' do
  pod 'HandTracker', :path => '../'

  target 'HandTracker_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
